/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.parser;

import lParser.lexer.*;
import lParser.node.*;
import lParser.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList<Object> listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgramme node1 = (PProgramme) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AVide$11Programme */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list);
            }
            break;
            case 1: /* reduce APrem1Programme */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list);
            }
            break;
            case 2: /* reduce AOuExp */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list);
            }
            break;
            case 3: /* reduce ANextExp */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list);
            }
            break;
            case 4: /* reduce AEtExp1 */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list);
            }
            break;
            case 5: /* reduce ANextExp1 */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list);
            }
            break;
            case 6: /* reduce AEgalExp2 */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list);
            }
            break;
            case 7: /* reduce ALessExp2 */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list);
            }
            break;
            case 8: /* reduce ANextExp2 */
            {
                ArrayList<Object> list = new8();
                push(goTo(3), list);
            }
            break;
            case 9: /* reduce AAddExp3 */
            {
                ArrayList<Object> list = new9();
                push(goTo(4), list);
            }
            break;
            case 10: /* reduce ASubExp3 */
            {
                ArrayList<Object> list = new10();
                push(goTo(4), list);
            }
            break;
            case 11: /* reduce ANextExp3 */
            {
                ArrayList<Object> list = new11();
                push(goTo(4), list);
            }
            break;
            case 12: /* reduce AMultiExp4 */
            {
                ArrayList<Object> list = new12();
                push(goTo(5), list);
            }
            break;
            case 13: /* reduce ADivisExp4 */
            {
                ArrayList<Object> list = new13();
                push(goTo(5), list);
            }
            break;
            case 14: /* reduce ANextExp4 */
            {
                ArrayList<Object> list = new14();
                push(goTo(5), list);
            }
            break;
            case 15: /* reduce ANonExp5 */
            {
                ArrayList<Object> list = new15();
                push(goTo(6), list);
            }
            break;
            case 16: /* reduce ANextExp5 */
            {
                ArrayList<Object> list = new16();
                push(goTo(6), list);
            }
            break;
            case 17: /* reduce AParExp6 */
            {
                ArrayList<Object> list = new17();
                push(goTo(7), list);
            }
            break;
            case 18: /* reduce ANumExp6 */
            {
                ArrayList<Object> list = new18();
                push(goTo(7), list);
            }
            break;
            case 19: /* reduce AVarExp6 */
            {
                ArrayList<Object> list = new19();
                push(goTo(7), list);
            }
            break;
            case 20: /* reduce AAppfExp6 */
            {
                ArrayList<Object> list = new20();
                push(goTo(7), list);
            }
            break;
            case 21: /* reduce AVraiExp6 */
            {
                ArrayList<Object> list = new21();
                push(goTo(7), list);
            }
            break;
            case 22: /* reduce AFauxExp6 */
            {
                ArrayList<Object> list = new22();
                push(goTo(7), list);
            }
            break;
            case 23: /* reduce AAffectI */
            {
                ArrayList<Object> list = new23();
                push(goTo(8), list);
            }
            break;
            case 24: /* reduce ATqI */
            {
                ArrayList<Object> list = new24();
                push(goTo(8), list);
            }
            break;
            case 25: /* reduce ASiI */
            {
                ArrayList<Object> list = new25();
                push(goTo(8), list);
            }
            break;
            case 26: /* reduce ASinonI */
            {
                ArrayList<Object> list = new26();
                push(goTo(8), list);
            }
            break;
            case 27: /* reduce ARetourI */
            {
                ArrayList<Object> list = new27();
                push(goTo(8), list);
            }
            break;
            case 28: /* reduce AAppfI */
            {
                ArrayList<Object> list = new28();
                push(goTo(8), list);
            }
            break;
            case 29: /* reduce AEcrireI */
            {
                ArrayList<Object> list = new29();
                push(goTo(8), list);
            }
            break;
            case 30: /* reduce ABi */
            {
                ArrayList<Object> list = new30();
                push(goTo(9), list);
            }
            break;
            case 31: /* reduce ARecurLi */
            {
                ArrayList<Object> list = new31();
                push(goTo(10), list);
            }
            break;
            case 32: /* reduce AVide$1Li */
            {
                ArrayList<Object> list = new32();
                push(goTo(10), list);
            }
            break;
            case 33: /* reduce AVarDv */
            {
                ArrayList<Object> list = new33();
                push(goTo(11), list);
            }
            break;
            case 34: /* reduce ATabDv */
            {
                ArrayList<Object> list = new34();
                push(goTo(11), list);
            }
            break;
            case 35: /* reduce AVide$11$Vide$12$Vide$11Df */
            {
                ArrayList<Object> list = new35();
                push(goTo(12), list);
            }
            break;
            case 36: /* reduce AVide$11$Vide$12$Type1Df */
            {
                ArrayList<Object> list = new36();
                push(goTo(12), list);
            }
            break;
            case 37: /* reduce AVide$11$Prem2$Vide$11Df */
            {
                ArrayList<Object> list = new37();
                push(goTo(12), list);
            }
            break;
            case 38: /* reduce AVide$11$Prem2$Type1Df */
            {
                ArrayList<Object> list = new38();
                push(goTo(12), list);
            }
            break;
            case 39: /* reduce APrem1$Vide$12$Vide$11Df */
            {
                ArrayList<Object> list = new39();
                push(goTo(12), list);
            }
            break;
            case 40: /* reduce APrem1$Vide$12$Type1Df */
            {
                ArrayList<Object> list = new40();
                push(goTo(12), list);
            }
            break;
            case 41: /* reduce APrem1$Prem2$Vide$11Df */
            {
                ArrayList<Object> list = new41();
                push(goTo(12), list);
            }
            break;
            case 42: /* reduce APrem1$Prem2$Type1Df */
            {
                ArrayList<Object> list = new42();
                push(goTo(12), list);
            }
            break;
            case 43: /* reduce AVide$1Ldvb */
            {
                ArrayList<Object> list = new43();
                push(goTo(13), list);
            }
            break;
            case 44: /* reduce ASuiteLdvb */
            {
                ArrayList<Object> list = new44();
                push(goTo(13), list);
            }
            break;
            case 45: /* reduce AIntType */
            {
                ArrayList<Object> list = new45();
                push(goTo(14), list);
            }
            break;
            case 46: /* reduce ABoolType */
            {
                ArrayList<Object> list = new46();
                push(goTo(14), list);
            }
            break;
            case 47: /* reduce AVarV */
            {
                ArrayList<Object> list = new47();
                push(goTo(15), list);
            }
            break;
            case 48: /* reduce ATabV */
            {
                ArrayList<Object> list = new48();
                push(goTo(15), list);
            }
            break;
            case 49: /* reduce AAf */
            {
                ArrayList<Object> list = new49();
                push(goTo(16), list);
            }
            break;
            case 50: /* reduce AVide$1Le */
            {
                ArrayList<Object> list = new50();
                push(goTo(17), list);
            }
            break;
            case 51: /* reduce APremLe */
            {
                ArrayList<Object> list = new51();
                push(goTo(17), list);
            }
            break;
            case 52: /* reduce AVide$1Leb */
            {
                ArrayList<Object> list = new52();
                push(goTo(18), list);
            }
            break;
            case 53: /* reduce ASuiteLeb */
            {
                ArrayList<Object> list = new53();
                push(goTo(18), list);
            }
            break;
            case 54: /* reduce AVide$1Ldf */
            {
                ArrayList<Object> list = new54();
                push(goTo(19), list);
            }
            break;
            case 55: /* reduce AElemLdf */
            {
                ArrayList<Object> list = new55();
                push(goTo(19), list);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AVide$11Programme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PLdv pldvNode2;
        PLdf pldfNode4;
        {
            // Block
        PEps pepsNode3;
        {
            // Block

        pepsNode3 = new AEps();
        }

        pldvNode2 = new AVideLdv(pepsNode3);
        }
        pldfNode4 = (PLdf)nodeArrayList1.get(0);

        pprogrammeNode1 = new AProgramme(pldvNode2, pldfNode4);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce APrem1Programme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PLdv pldvNode2;
        PLdf pldfNode5;
        {
            // Block
        PDv pdvNode3;
        PLdvb pldvbNode4;
        pdvNode3 = (PDv)nodeArrayList1.get(0);
        pldvbNode4 = (PLdvb)nodeArrayList2.get(0);

        pldvNode2 = new APremLdv(pdvNode3, pldvbNode4);
        }
        pldfNode5 = (PLdf)nodeArrayList3.get(0);

        pprogrammeNode1 = new AProgramme(pldvNode2, pldfNode5);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AOuExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TOu touNode3;
        PExp1 pexp1Node4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        touNode3 = (TOu)nodeArrayList2.get(0);
        pexp1Node4 = (PExp1)nodeArrayList3.get(0);

        pexpNode1 = new AOuExp(pexpNode2, touNode3, pexp1Node4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce ANextExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp1 pexp1Node2;
        pexp1Node2 = (PExp1)nodeArrayList1.get(0);

        pexpNode1 = new ANextExp(pexp1Node2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AEtExp1 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp1 pexp1Node1;
        {
            // Block
        PExp1 pexp1Node2;
        TEt tetNode3;
        PExp2 pexp2Node4;
        pexp1Node2 = (PExp1)nodeArrayList1.get(0);
        tetNode3 = (TEt)nodeArrayList2.get(0);
        pexp2Node4 = (PExp2)nodeArrayList3.get(0);

        pexp1Node1 = new AEtExp1(pexp1Node2, tetNode3, pexp2Node4);
        }
	nodeList.add(pexp1Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ANextExp1 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp1 pexp1Node1;
        {
            // Block
        PExp2 pexp2Node2;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);

        pexp1Node1 = new ANextExp1(pexp2Node2);
        }
	nodeList.add(pexp1Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AEgalExp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp2 pexp2Node2;
        TEgal tegalNode3;
        PExp3 pexp3Node4;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);
        tegalNode3 = (TEgal)nodeArrayList2.get(0);
        pexp3Node4 = (PExp3)nodeArrayList3.get(0);

        pexp2Node1 = new AEgalExp2(pexp2Node2, tegalNode3, pexp3Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce ALessExp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp2 pexp2Node2;
        TLess tlessNode3;
        PExp3 pexp3Node4;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);
        tlessNode3 = (TLess)nodeArrayList2.get(0);
        pexp3Node4 = (PExp3)nodeArrayList3.get(0);

        pexp2Node1 = new ALessExp2(pexp2Node2, tlessNode3, pexp3Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ANextExp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp3 pexp3Node2;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);

        pexp2Node1 = new ANextExp2(pexp3Node2);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AAddExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TPlus tplusNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new AAddExp3(pexp3Node2, tplusNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ASubExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TMoins tmoinsNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tmoinsNode3 = (TMoins)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new ASubExp3(pexp3Node2, tmoinsNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ANextExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp4 pexp4Node2;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);

        pexp3Node1 = new ANextExp3(pexp4Node2);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AMultiExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TMulti tmultiNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tmultiNode3 = (TMulti)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new AMultiExp4(pexp4Node2, tmultiNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ADivisExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TDivis tdivisNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tdivisNode3 = (TDivis)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new ADivisExp4(pexp4Node2, tdivisNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce ANextExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp5 pexp5Node2;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);

        pexp4Node1 = new ANextExp4(pexp5Node2);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce ANonExp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        TNon tnonNode2;
        PExp6 pexp6Node3;
        tnonNode2 = (TNon)nodeArrayList1.get(0);
        pexp6Node3 = (PExp6)nodeArrayList2.get(0);

        pexp5Node1 = new ANonExp5(tnonNode2, pexp6Node3);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce ANextExp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp6 pexp6Node2;
        pexp6Node2 = (PExp6)nodeArrayList1.get(0);

        pexp5Node1 = new ANextExp5(pexp6Node2);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AParExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TPo tpoNode2;
        PExp1 pexp1Node3;
        TPf tpfNode4;
        tpoNode2 = (TPo)nodeArrayList1.get(0);
        pexp1Node3 = (PExp1)nodeArrayList2.get(0);
        tpfNode4 = (TPf)nodeArrayList3.get(0);

        pexp6Node1 = new AParExp6(tpoNode2, pexp1Node3, tpfNode4);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce ANumExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TNombre tnombreNode2;
        tnombreNode2 = (TNombre)nodeArrayList1.get(0);

        pexp6Node1 = new ANumExp6(tnombreNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AVarExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        PV pvNode2;
        pvNode2 = (PV)nodeArrayList1.get(0);

        pexp6Node1 = new AVarExp6(pvNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AAppfExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        PAf pafNode2;
        pafNode2 = (PAf)nodeArrayList1.get(0);

        pexp6Node1 = new AAppfExp6(pafNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AVraiExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TVrai tvraiNode2;
        tvraiNode2 = (TVrai)nodeArrayList1.get(0);

        pexp6Node1 = new AVraiExp6(tvraiNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AFauxExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TFaux tfauxNode2;
        tfauxNode2 = (TFaux)nodeArrayList1.get(0);

        pexp6Node1 = new AFauxExp6(tfauxNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AAffectI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        PV pvNode2;
        TEgal tegalNode3;
        PExp pexpNode4;
        TPv tpvNode5;
        pvNode2 = (PV)nodeArrayList1.get(0);
        tegalNode3 = (TEgal)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tpvNode5 = (TPv)nodeArrayList4.get(0);

        piNode1 = new AAffectI(pvNode2, tegalNode3, pexpNode4, tpvNode5);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce ATqI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TTq ttqNode2;
        PExp pexpNode3;
        TFaire tfaireNode4;
        PBi pbiNode5;
        ttqNode2 = (TTq)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tfaireNode4 = (TFaire)nodeArrayList3.get(0);
        pbiNode5 = (PBi)nodeArrayList4.get(0);

        piNode1 = new ATqI(ttqNode2, pexpNode3, tfaireNode4, pbiNode5);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce ASiI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TSi tsiNode2;
        PExp pexpNode3;
        TAlors talorsNode4;
        PBi pbiNode5;
        tsiNode2 = (TSi)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        talorsNode4 = (TAlors)nodeArrayList3.get(0);
        pbiNode5 = (PBi)nodeArrayList4.get(0);

        piNode1 = new ASiI(tsiNode2, pexpNode3, talorsNode4, pbiNode5);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce ASinonI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TSi tsiNode2;
        PExp pexpNode3;
        TAlors talorsNode4;
        PBi pbiNode5;
        TSinon tsinonNode6;
        PBi pbiNode7;
        tsiNode2 = (TSi)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        talorsNode4 = (TAlors)nodeArrayList3.get(0);
        pbiNode5 = (PBi)nodeArrayList4.get(0);
        tsinonNode6 = (TSinon)nodeArrayList5.get(0);
        pbiNode7 = (PBi)nodeArrayList6.get(0);

        piNode1 = new ASinonI(tsiNode2, pexpNode3, talorsNode4, pbiNode5, tsinonNode6, pbiNode7);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce ARetourI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TRetour tretourNode2;
        PExp pexpNode3;
        TPv tpvNode4;
        tretourNode2 = (TRetour)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tpvNode4 = (TPv)nodeArrayList3.get(0);

        piNode1 = new ARetourI(tretourNode2, pexpNode3, tpvNode4);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AAppfI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        PAf pafNode2;
        TPv tpvNode3;
        pafNode2 = (PAf)nodeArrayList1.get(0);
        tpvNode3 = (TPv)nodeArrayList2.get(0);

        piNode1 = new AAppfI(pafNode2, tpvNode3);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AEcrireI */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PI piNode1;
        {
            // Block
        TEcrire tecrireNode2;
        TPo tpoNode3;
        PExp pexpNode4;
        TPf tpfNode5;
        TPv tpvNode6;
        tecrireNode2 = (TEcrire)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);
        tpvNode6 = (TPv)nodeArrayList5.get(0);

        piNode1 = new AEcrireI(tecrireNode2, tpoNode3, pexpNode4, tpfNode5, tpvNode6);
        }
	nodeList.add(piNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce ABi */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PBi pbiNode1;
        {
            // Block
        TAco tacoNode2;
        PLi pliNode3;
        TAcf tacfNode4;
        tacoNode2 = (TAco)nodeArrayList1.get(0);
        pliNode3 = (PLi)nodeArrayList2.get(0);
        tacfNode4 = (TAcf)nodeArrayList3.get(0);

        pbiNode1 = new ABi(tacoNode2, pliNode3, tacfNode4);
        }
	nodeList.add(pbiNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce ARecurLi */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLi pliNode1;
        {
            // Block
        PLi pliNode2;
        PI piNode3;
        pliNode2 = (PLi)nodeArrayList1.get(0);
        piNode3 = (PI)nodeArrayList2.get(0);

        pliNode1 = new ARecurLi(pliNode2, piNode3);
        }
	nodeList.add(pliNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AVide$1Li */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLi pliNode1;
        {
            // Block
        PEps pepsNode2;
        {
            // Block

        pepsNode2 = new AEps();
        }

        pliNode1 = new AVideLi(pepsNode2);
        }
	nodeList.add(pliNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AVarDv */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDv pdvNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pdvNode1 = new AVarDv(ptypeNode2, tidNode3);
        }
	nodeList.add(pdvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce ATabDv */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDv pdvNode1;
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        TCro tcroNode4;
        TNombre tnombreNode5;
        TCrf tcrfNode6;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tcroNode4 = (TCro)nodeArrayList3.get(0);
        tnombreNode5 = (TNombre)nodeArrayList4.get(0);
        tcrfNode6 = (TCrf)nodeArrayList5.get(0);

        pdvNode1 = new ATabDv(ptypeNode2, tidNode3, tcroNode4, tnombreNode5, tcrfNode6);
        }
	nodeList.add(pdvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AVide$11$Vide$12$Vide$11Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode8;
        PLdv pldvNode9;
        PBi pbiNode11;
        {
            // Block
        PEps pepsNode3;
        {
            // Block

        pepsNode3 = new AEps();
        }

        ptypeoptNode2 = new AVideTypeopt(pepsNode3);
        }
        tidNode4 = (TId)nodeArrayList1.get(0);
        tpoNode5 = (TPo)nodeArrayList2.get(0);
        {
            // Block
        PEps pepsNode7;
        {
            // Block

        pepsNode7 = new AEps();
        }

        pldvNode6 = new AVideLdv(pepsNode7);
        }
        tpfNode8 = (TPf)nodeArrayList3.get(0);
        {
            // Block
        PEps pepsNode10;
        {
            // Block

        pepsNode10 = new AEps();
        }

        pldvNode9 = new AVideLdv(pepsNode10);
        }
        pbiNode11 = (PBi)nodeArrayList4.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode8, pldvNode9, pbiNode11);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AVide$11$Vide$12$Type1Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode8;
        PLdv pldvNode9;
        PBi pbiNode11;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        ptypeoptNode2 = new ATypeTypeopt(ptypeNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block
        PEps pepsNode7;
        {
            // Block

        pepsNode7 = new AEps();
        }

        pldvNode6 = new AVideLdv(pepsNode7);
        }
        tpfNode8 = (TPf)nodeArrayList4.get(0);
        {
            // Block
        PEps pepsNode10;
        {
            // Block

        pepsNode10 = new AEps();
        }

        pldvNode9 = new AVideLdv(pepsNode10);
        }
        pbiNode11 = (PBi)nodeArrayList5.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode8, pldvNode9, pbiNode11);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce AVide$11$Prem2$Vide$11Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode8;
        PLdv pldvNode9;
        PBi pbiNode12;
        {
            // Block
        PEps pepsNode3;
        {
            // Block

        pepsNode3 = new AEps();
        }

        ptypeoptNode2 = new AVideTypeopt(pepsNode3);
        }
        tidNode4 = (TId)nodeArrayList1.get(0);
        tpoNode5 = (TPo)nodeArrayList2.get(0);
        {
            // Block
        PEps pepsNode7;
        {
            // Block

        pepsNode7 = new AEps();
        }

        pldvNode6 = new AVideLdv(pepsNode7);
        }
        tpfNode8 = (TPf)nodeArrayList3.get(0);
        {
            // Block
        PDv pdvNode10;
        PLdvb pldvbNode11;
        pdvNode10 = (PDv)nodeArrayList4.get(0);
        pldvbNode11 = (PLdvb)nodeArrayList5.get(0);

        pldvNode9 = new APremLdv(pdvNode10, pldvbNode11);
        }
        pbiNode12 = (PBi)nodeArrayList6.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode8, pldvNode9, pbiNode12);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AVide$11$Prem2$Type1Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode8;
        PLdv pldvNode9;
        PBi pbiNode12;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        ptypeoptNode2 = new ATypeTypeopt(ptypeNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block
        PEps pepsNode7;
        {
            // Block

        pepsNode7 = new AEps();
        }

        pldvNode6 = new AVideLdv(pepsNode7);
        }
        tpfNode8 = (TPf)nodeArrayList4.get(0);
        {
            // Block
        PDv pdvNode10;
        PLdvb pldvbNode11;
        pdvNode10 = (PDv)nodeArrayList5.get(0);
        pldvbNode11 = (PLdvb)nodeArrayList6.get(0);

        pldvNode9 = new APremLdv(pdvNode10, pldvbNode11);
        }
        pbiNode12 = (PBi)nodeArrayList7.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode8, pldvNode9, pbiNode12);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce APrem1$Vide$12$Vide$11Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode9;
        PLdv pldvNode10;
        PBi pbiNode12;
        {
            // Block
        PEps pepsNode3;
        {
            // Block

        pepsNode3 = new AEps();
        }

        ptypeoptNode2 = new AVideTypeopt(pepsNode3);
        }
        tidNode4 = (TId)nodeArrayList1.get(0);
        tpoNode5 = (TPo)nodeArrayList2.get(0);
        {
            // Block
        PDv pdvNode7;
        PLdvb pldvbNode8;
        pdvNode7 = (PDv)nodeArrayList3.get(0);
        pldvbNode8 = (PLdvb)nodeArrayList4.get(0);

        pldvNode6 = new APremLdv(pdvNode7, pldvbNode8);
        }
        tpfNode9 = (TPf)nodeArrayList5.get(0);
        {
            // Block
        PEps pepsNode11;
        {
            // Block

        pepsNode11 = new AEps();
        }

        pldvNode10 = new AVideLdv(pepsNode11);
        }
        pbiNode12 = (PBi)nodeArrayList6.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode9, pldvNode10, pbiNode12);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce APrem1$Vide$12$Type1Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode9;
        PLdv pldvNode10;
        PBi pbiNode12;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        ptypeoptNode2 = new ATypeTypeopt(ptypeNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block
        PDv pdvNode7;
        PLdvb pldvbNode8;
        pdvNode7 = (PDv)nodeArrayList4.get(0);
        pldvbNode8 = (PLdvb)nodeArrayList5.get(0);

        pldvNode6 = new APremLdv(pdvNode7, pldvbNode8);
        }
        tpfNode9 = (TPf)nodeArrayList6.get(0);
        {
            // Block
        PEps pepsNode11;
        {
            // Block

        pepsNode11 = new AEps();
        }

        pldvNode10 = new AVideLdv(pepsNode11);
        }
        pbiNode12 = (PBi)nodeArrayList7.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode9, pldvNode10, pbiNode12);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce APrem1$Prem2$Vide$11Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode9;
        PLdv pldvNode10;
        PBi pbiNode13;
        {
            // Block
        PEps pepsNode3;
        {
            // Block

        pepsNode3 = new AEps();
        }

        ptypeoptNode2 = new AVideTypeopt(pepsNode3);
        }
        tidNode4 = (TId)nodeArrayList1.get(0);
        tpoNode5 = (TPo)nodeArrayList2.get(0);
        {
            // Block
        PDv pdvNode7;
        PLdvb pldvbNode8;
        pdvNode7 = (PDv)nodeArrayList3.get(0);
        pldvbNode8 = (PLdvb)nodeArrayList4.get(0);

        pldvNode6 = new APremLdv(pdvNode7, pldvbNode8);
        }
        tpfNode9 = (TPf)nodeArrayList5.get(0);
        {
            // Block
        PDv pdvNode11;
        PLdvb pldvbNode12;
        pdvNode11 = (PDv)nodeArrayList6.get(0);
        pldvbNode12 = (PLdvb)nodeArrayList7.get(0);

        pldvNode10 = new APremLdv(pdvNode11, pldvbNode12);
        }
        pbiNode13 = (PBi)nodeArrayList8.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode9, pldvNode10, pbiNode13);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce APrem1$Prem2$Type1Df */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDf pdfNode1;
        {
            // Block
        PTypeopt ptypeoptNode2;
        TId tidNode4;
        TPo tpoNode5;
        PLdv pldvNode6;
        TPf tpfNode9;
        PLdv pldvNode10;
        PBi pbiNode13;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        ptypeoptNode2 = new ATypeTypeopt(ptypeNode3);
        }
        tidNode4 = (TId)nodeArrayList2.get(0);
        tpoNode5 = (TPo)nodeArrayList3.get(0);
        {
            // Block
        PDv pdvNode7;
        PLdvb pldvbNode8;
        pdvNode7 = (PDv)nodeArrayList4.get(0);
        pldvbNode8 = (PLdvb)nodeArrayList5.get(0);

        pldvNode6 = new APremLdv(pdvNode7, pldvbNode8);
        }
        tpfNode9 = (TPf)nodeArrayList6.get(0);
        {
            // Block
        PDv pdvNode11;
        PLdvb pldvbNode12;
        pdvNode11 = (PDv)nodeArrayList7.get(0);
        pldvbNode12 = (PLdvb)nodeArrayList8.get(0);

        pldvNode10 = new APremLdv(pdvNode11, pldvbNode12);
        }
        pbiNode13 = (PBi)nodeArrayList9.get(0);

        pdfNode1 = new ADf(ptypeoptNode2, tidNode4, tpoNode5, pldvNode6, tpfNode9, pldvNode10, pbiNode13);
        }
	nodeList.add(pdfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce AVide$1Ldvb */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLdvb pldvbNode1;
        {
            // Block
        PEps pepsNode2;
        {
            // Block

        pepsNode2 = new AEps();
        }

        pldvbNode1 = new AVideLdvb(pepsNode2);
        }
	nodeList.add(pldvbNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce ASuiteLdvb */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLdvb pldvbNode1;
        {
            // Block
        TVir tvirNode2;
        PDv pdvNode3;
        PLdvb pldvbNode4;
        tvirNode2 = (TVir)nodeArrayList1.get(0);
        pdvNode3 = (PDv)nodeArrayList2.get(0);
        pldvbNode4 = (PLdvb)nodeArrayList3.get(0);

        pldvbNode1 = new ASuiteLdvb(tvirNode2, pdvNode3, pldvbNode4);
        }
	nodeList.add(pldvbNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AIntType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TEntier tentierNode2;
        tentierNode2 = (TEntier)nodeArrayList1.get(0);

        ptypeNode1 = new AIntType(tentierNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce ABoolType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TBool tboolNode2;
        tboolNode2 = (TBool)nodeArrayList1.get(0);

        ptypeNode1 = new ABoolType(tboolNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce AVarV */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PV pvNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pvNode1 = new AVarV(tidNode2);
        }
	nodeList.add(pvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce ATabV */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PV pvNode1;
        {
            // Block
        TId tidNode2;
        TCro tcroNode3;
        PExp pexpNode4;
        TCrf tcrfNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tcroNode3 = (TCro)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tcrfNode5 = (TCrf)nodeArrayList4.get(0);

        pvNode1 = new ATabV(tidNode2, tcroNode3, pexpNode4, tcrfNode5);
        }
	nodeList.add(pvNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce AAf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAf pafNode1;
        {
            // Block
        TId tidNode2;
        TPo tpoNode3;
        PLe pleNode4;
        TPf tpfNode5;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tpoNode3 = (TPo)nodeArrayList2.get(0);
        pleNode4 = (PLe)nodeArrayList3.get(0);
        tpfNode5 = (TPf)nodeArrayList4.get(0);

        pafNode1 = new AAf(tidNode2, tpoNode3, pleNode4, tpfNode5);
        }
	nodeList.add(pafNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce AVide$1Le */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLe pleNode1;
        {
            // Block
        PEps pepsNode2;
        {
            // Block

        pepsNode2 = new AEps();
        }

        pleNode1 = new AVideLe(pepsNode2);
        }
	nodeList.add(pleNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce APremLe */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLe pleNode1;
        {
            // Block
        PExp pexpNode2;
        PLeb plebNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        plebNode3 = (PLeb)nodeArrayList2.get(0);

        pleNode1 = new APremLe(pexpNode2, plebNode3);
        }
	nodeList.add(pleNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce AVide$1Leb */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLeb plebNode1;
        {
            // Block
        PEps pepsNode2;
        {
            // Block

        pepsNode2 = new AEps();
        }

        plebNode1 = new AVideLeb(pepsNode2);
        }
	nodeList.add(plebNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce ASuiteLeb */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLeb plebNode1;
        {
            // Block
        TVir tvirNode2;
        PExp pexpNode3;
        PLeb plebNode4;
        tvirNode2 = (TVir)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        plebNode4 = (PLeb)nodeArrayList3.get(0);

        plebNode1 = new ASuiteLeb(tvirNode2, pexpNode3, plebNode4);
        }
	nodeList.add(plebNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce AVide$1Ldf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PLdf pldfNode1;
        {
            // Block
        PEps pepsNode2;
        {
            // Block

        pepsNode2 = new AEps();
        }

        pldfNode1 = new AVideLdf(pepsNode2);
        }
	nodeList.add(pldfNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce AElemLdf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PLdf pldfNode1;
        {
            // Block
        PDf pdfNode2;
        PLdf pldfNode3;
        pdfNode2 = (PDf)nodeArrayList1.get(0);
        pldfNode3 = (PLdf)nodeArrayList2.get(0);

        pldfNode1 = new AElemLdf(pdfNode2, pldfNode3);
        }
	nodeList.add(pldfNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 54}, {27, SHIFT, 1}, {28, SHIFT, 2}, {29, SHIFT, 3}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 46}, },
			{{-1, ERROR, 3}, {10, SHIFT, 9}, },
			{{-1, ERROR, 4}, {30, ACCEPT, -1}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 54}, {27, SHIFT, 1}, {28, SHIFT, 2}, {29, SHIFT, 3}, },
			{{-1, ERROR, 7}, {29, SHIFT, 14}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 9}, {11, SHIFT, 15}, {27, SHIFT, 1}, {28, SHIFT, 2}, },
			{{-1, ERROR, 10}, {27, SHIFT, 1}, {28, SHIFT, 2}, },
			{{-1, REDUCE, 54}, {27, SHIFT, 1}, {28, SHIFT, 2}, {29, SHIFT, 3}, },
			{{-1, ERROR, 12}, {29, SHIFT, 20}, },
			{{-1, REDUCE, 55}, },
			{{-1, REDUCE, 33}, {10, SHIFT, 21}, {24, SHIFT, 22}, },
			{{-1, ERROR, 15}, {22, SHIFT, 23}, {27, SHIFT, 1}, {28, SHIFT, 2}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, ERROR, 17}, {29, SHIFT, 27}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 20}, {10, SHIFT, 21}, },
			{{-1, ERROR, 21}, {11, SHIFT, 29}, {27, SHIFT, 1}, {28, SHIFT, 2}, },
			{{-1, ERROR, 22}, {1, SHIFT, 31}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, ERROR, 26}, {11, SHIFT, 34}, },
			{{-1, REDUCE, 33}, {24, SHIFT, 22}, },
			{{-1, REDUCE, 44}, },
			{{-1, ERROR, 29}, {22, SHIFT, 23}, {27, SHIFT, 1}, {28, SHIFT, 2}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, ERROR, 31}, {25, SHIFT, 38}, },
			{{-1, ERROR, 32}, {15, SHIFT, 39}, {17, SHIFT, 40}, {20, SHIFT, 41}, {21, SHIFT, 42}, {23, SHIFT, 43}, {29, SHIFT, 44}, },
			{{-1, ERROR, 33}, {22, SHIFT, 23}, },
			{{-1, ERROR, 34}, {22, SHIFT, 23}, {27, SHIFT, 1}, {28, SHIFT, 2}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, ERROR, 37}, {11, SHIFT, 52}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 39}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 40}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 41}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 42}, {10, SHIFT, 69}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 47}, {10, SHIFT, 70}, {24, SHIFT, 71}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 46}, {4, SHIFT, 72}, },
			{{-1, ERROR, 47}, {14, SHIFT, 73}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, ERROR, 51}, {22, SHIFT, 23}, },
			{{-1, ERROR, 52}, {22, SHIFT, 23}, {27, SHIFT, 1}, {28, SHIFT, 2}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 54}, {1, SHIFT, 53}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 55}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 22}, },
			{{-1, ERROR, 58}, {2, SHIFT, 80}, {16, SHIFT, 81}, },
			{{-1, REDUCE, 3}, {3, SHIFT, 82}, },
			{{-1, REDUCE, 5}, {4, SHIFT, 83}, {5, SHIFT, 84}, },
			{{-1, REDUCE, 8}, {0, SHIFT, 85}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 11}, {7, SHIFT, 87}, {8, SHIFT, 88}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 67}, {2, SHIFT, 80}, {18, SHIFT, 89}, },
			{{-1, ERROR, 68}, {2, SHIFT, 80}, {14, SHIFT, 90}, },
			{{-1, ERROR, 69}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, REDUCE, 50}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 71}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 72}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 74}, {22, SHIFT, 23}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 43}, {26, SHIFT, 10}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 79}, {3, SHIFT, 82}, {11, SHIFT, 98}, },
			{{-1, ERROR, 80}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 81}, {22, SHIFT, 23}, },
			{{-1, ERROR, 82}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 83}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 84}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 85}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 86}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 87}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 88}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, ERROR, 89}, {22, SHIFT, 23}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 91}, {2, SHIFT, 80}, {11, SHIFT, 109}, },
			{{-1, REDUCE, 52}, {2, SHIFT, 80}, {26, SHIFT, 110}, },
			{{-1, ERROR, 93}, {11, SHIFT, 112}, },
			{{-1, ERROR, 94}, {2, SHIFT, 80}, {25, SHIFT, 113}, },
			{{-1, ERROR, 95}, {2, SHIFT, 80}, {14, SHIFT, 114}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 97}, {22, SHIFT, 23}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 2}, {3, SHIFT, 82}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 4}, {4, SHIFT, 83}, {5, SHIFT, 84}, },
			{{-1, REDUCE, 6}, {0, SHIFT, 85}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 7}, {0, SHIFT, 85}, {6, SHIFT, 86}, },
			{{-1, REDUCE, 9}, {7, SHIFT, 87}, {8, SHIFT, 88}, },
			{{-1, REDUCE, 10}, {7, SHIFT, 87}, {8, SHIFT, 88}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 25}, {19, SHIFT, 116}, },
			{{-1, ERROR, 109}, {14, SHIFT, 117}, },
			{{-1, ERROR, 110}, {1, SHIFT, 53}, {9, SHIFT, 54}, {10, SHIFT, 55}, {12, SHIFT, 56}, {13, SHIFT, 57}, {29, SHIFT, 44}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 42}, },
			{{-1, ERROR, 116}, {22, SHIFT, 23}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 52}, {2, SHIFT, 80}, {26, SHIFT, 110}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 53}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 4}, },
			{{-1, 58}, {40, 67}, {41, 68}, {69, 91}, {70, 92}, {71, 94}, {72, 95}, {110, 118}, },
			{{-1, 59}, {55, 79}, {80, 99}, },
			{{-1, 60}, {82, 101}, },
			{{-1, 61}, {83, 102}, {84, 103}, },
			{{-1, 62}, {85, 104}, {86, 105}, },
			{{-1, 63}, {87, 106}, {88, 107}, },
			{{-1, 64}, {54, 78}, },
			{{-1, 45}, },
			{{-1, 24}, {29, 35}, {33, 48}, {34, 49}, {51, 75}, {52, 76}, {74, 96}, {81, 100}, {89, 108}, {97, 115}, {116, 119}, },
			{{-1, 32}, },
			{{-1, 5}, {9, 16}, {10, 18}, {15, 25}, {21, 30}, {29, 36}, {34, 50}, {52, 77}, },
			{{-1, 6}, },
			{{-1, 11}, {16, 26}, {18, 28}, {25, 33}, {30, 37}, {36, 51}, {50, 74}, {77, 97}, },
			{{-1, 17}, {0, 7}, {6, 12}, {11, 12}, },
			{{-1, 65}, {32, 46}, },
			{{-1, 66}, {32, 47}, },
			{{-1, 93}, },
			{{-1, 111}, {118, 120}, },
			{{-1, 8}, {6, 13}, {11, 19}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'entier', 'bool', id, EOF",
			"expecting: id",
			"expecting: '('",
			"expecting: EOF",
			"expecting: ',', 'entier', 'bool', id, EOF",
			"expecting: ')', 'entier', 'bool'",
			"expecting: 'entier', 'bool'",
			"expecting: '(', '[', ',', 'entier', 'bool', id, EOF",
			"expecting: '{', 'entier', 'bool'",
			"expecting: ')', ','",
			"expecting: ')', '{', ',', 'entier', 'bool', id, EOF",
			"expecting: nombre",
			"expecting: 'tantque', 'si', 'retour', 'ecrire', '}', id",
			"expecting: '{', ','",
			"expecting: ')'",
			"expecting: ')', '{', '[', ',', 'entier', 'bool', id, EOF",
			"expecting: ')', '{', 'entier', 'bool', id, EOF",
			"expecting: ']'",
			"expecting: '{'",
			"expecting: nombre, '!', '(', 'Vrai', 'Faux', id",
			"expecting: 'tantque', 'si', 'sinon', 'retour', 'ecrire', '}', 'entier', 'bool', id, EOF",
			"expecting: '+', '|', '&', '=', '<', '-', '*', '/', '(', ')', ';', 'faire', 'alors', '[', ']', ','",
			"expecting: '='",
			"expecting: ';'",
			"expecting: '+', '|', '&', '=', '<', '-', '*', '/', ')', ';', 'faire', 'alors', ']', ','",
			"expecting: nombre, '(', 'Vrai', 'Faux', id",
			"expecting: '|', 'faire'",
			"expecting: '|', '&', ')', ';', 'faire', 'alors', ']', ','",
			"expecting: '|', '&', '=', '<', ')', ';', 'faire', 'alors', ']', ','",
			"expecting: '+', '|', '&', '=', '<', '-', ')', ';', 'faire', 'alors', ']', ','",
			"expecting: '|', 'alors'",
			"expecting: '|', ';'",
			"expecting: nombre, '!', '(', ')', 'Vrai', 'Faux', id",
			"expecting: '&', ')'",
			"expecting: '|', ')'",
			"expecting: '|', ')', ','",
			"expecting: '|', ']'",
			"expecting: 'tantque', 'si', 'sinon', 'retour', 'ecrire', '}', id",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 3, 4, 0, 1, 3, 5, 6, 0, 1, 3, 7, 8, 9, 1, 10, 3, 2, 5, 11, 12, 0, 13, 14, 15, 16, 8, 9, 17, 12, 18, 8, 0, 13, 14, 10, 19, 19, 19, 2, 20, 21, 12, 22, 23, 0, 0, 13, 18, 8, 24, 25, 19, 24, 24, 26, 27, 28, 29, 24, 24, 24, 24, 24, 30, 31, 19, 32, 19, 19, 12, 18, 0, 0, 13, 24, 33, 19, 18, 19, 19, 19, 19, 19, 19, 19, 18, 12, 34, 35, 14, 36, 31, 0, 18, 24, 27, 12, 28, 29, 29, 24, 24, 24, 24, 37, 23, 19, 14, 24, 24, 12, 0, 18, 12, 35, 12, 14, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
