/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.analysis;

import java.util.*;
import lParser.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgramme(AProgramme node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExp(AOuExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANextExp(ANextExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEtExp1(AEtExp1 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANextExp1(ANextExp1 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEgalExp2(AEgalExp2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALessExp2(ALessExp2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANextExp2(ANextExp2 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAddExp3(AAddExp3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubExp3(ASubExp3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANextExp3(ANextExp3 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiExp4(AMultiExp4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivisExp4(ADivisExp4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANextExp4(ANextExp4 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANonExp5(ANonExp5 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANextExp5(ANextExp5 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParExp6(AParExp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumExp6(ANumExp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarExp6(AVarExp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAppfExp6(AAppfExp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVraiExp6(AVraiExp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFauxExp6(AFauxExp6 node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAffectI(AAffectI node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATqI(ATqI node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASiI(ASiI node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASinonI(ASinonI node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARetourI(ARetourI node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAppfI(AAppfI node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEcrireI(AEcrireI node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABi(ABi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARecurLi(ARecurLi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLi(AVideLi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEps(AEps node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarDv(AVarDv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATabDv(ATabDv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADf(ADf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLdv(AVideLdv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPremLdv(APremLdv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLdvb(AVideLdvb node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASuiteLdvb(ASuiteLdvb node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideTypeopt(AVideTypeopt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATypeTypeopt(ATypeTypeopt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntType(AIntType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoolType(ABoolType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarV(AVarV node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATabV(ATabV node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAf(AAf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLe(AVideLe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPremLe(APremLe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLeb(AVideLeb node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASuiteLeb(ASuiteLeb node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVideLdf(AVideLdf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAElemLdf(AElemLdf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEspaces(TEspaces node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCommentaire(TCommentaire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNombre(TNombre node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEt(TEt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEgal(TEgal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLess(TLess node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMoins(TMoins node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMulti(TMulti node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDivis(TDivis node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNon(TNon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPo(TPo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPf(TPf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVrai(TVrai node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFaux(TFaux node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPv(TPv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTq(TTq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFaire(TFaire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSi(TSi node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAlors(TAlors node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSinon(TSinon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRetour(TRetour node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEcrire(TEcrire node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAco(TAco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAcf(TAcf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCro(TCro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCrf(TCrf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVir(TVir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEntier(TEntier node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBool(TBool node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
