/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.analysis;

import java.util.*;
import lParser.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgramme().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgramme(AProgramme node)
    {
        defaultIn(node);
    }

    public void outAProgramme(AProgramme node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgramme(AProgramme node)
    {
        inAProgramme(node);
        if(node.getLdv() != null)
        {
            node.getLdv().apply(this);
        }
        if(node.getLdf() != null)
        {
            node.getLdf().apply(this);
        }
        outAProgramme(node);
    }

    public void inAOuExp(AOuExp node)
    {
        defaultIn(node);
    }

    public void outAOuExp(AOuExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuExp(AOuExp node)
    {
        inAOuExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getOu() != null)
        {
            node.getOu().apply(this);
        }
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        outAOuExp(node);
    }

    public void inANextExp(ANextExp node)
    {
        defaultIn(node);
    }

    public void outANextExp(ANextExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANextExp(ANextExp node)
    {
        inANextExp(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        outANextExp(node);
    }

    public void inAEtExp1(AEtExp1 node)
    {
        defaultIn(node);
    }

    public void outAEtExp1(AEtExp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEtExp1(AEtExp1 node)
    {
        inAEtExp1(node);
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getEt() != null)
        {
            node.getEt().apply(this);
        }
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        outAEtExp1(node);
    }

    public void inANextExp1(ANextExp1 node)
    {
        defaultIn(node);
    }

    public void outANextExp1(ANextExp1 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANextExp1(ANextExp1 node)
    {
        inANextExp1(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        outANextExp1(node);
    }

    public void inAEgalExp2(AEgalExp2 node)
    {
        defaultIn(node);
    }

    public void outAEgalExp2(AEgalExp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEgalExp2(AEgalExp2 node)
    {
        inAEgalExp2(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        if(node.getEgal() != null)
        {
            node.getEgal().apply(this);
        }
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outAEgalExp2(node);
    }

    public void inALessExp2(ALessExp2 node)
    {
        defaultIn(node);
    }

    public void outALessExp2(ALessExp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessExp2(ALessExp2 node)
    {
        inALessExp2(node);
        if(node.getExp2() != null)
        {
            node.getExp2().apply(this);
        }
        if(node.getLess() != null)
        {
            node.getLess().apply(this);
        }
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outALessExp2(node);
    }

    public void inANextExp2(ANextExp2 node)
    {
        defaultIn(node);
    }

    public void outANextExp2(ANextExp2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANextExp2(ANextExp2 node)
    {
        inANextExp2(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        outANextExp2(node);
    }

    public void inAAddExp3(AAddExp3 node)
    {
        defaultIn(node);
    }

    public void outAAddExp3(AAddExp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAddExp3(AAddExp3 node)
    {
        inAAddExp3(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outAAddExp3(node);
    }

    public void inASubExp3(ASubExp3 node)
    {
        defaultIn(node);
    }

    public void outASubExp3(ASubExp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubExp3(ASubExp3 node)
    {
        inASubExp3(node);
        if(node.getExp3() != null)
        {
            node.getExp3().apply(this);
        }
        if(node.getMoins() != null)
        {
            node.getMoins().apply(this);
        }
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outASubExp3(node);
    }

    public void inANextExp3(ANextExp3 node)
    {
        defaultIn(node);
    }

    public void outANextExp3(ANextExp3 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANextExp3(ANextExp3 node)
    {
        inANextExp3(node);
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        outANextExp3(node);
    }

    public void inAMultiExp4(AMultiExp4 node)
    {
        defaultIn(node);
    }

    public void outAMultiExp4(AMultiExp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiExp4(AMultiExp4 node)
    {
        inAMultiExp4(node);
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        if(node.getMulti() != null)
        {
            node.getMulti().apply(this);
        }
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outAMultiExp4(node);
    }

    public void inADivisExp4(ADivisExp4 node)
    {
        defaultIn(node);
    }

    public void outADivisExp4(ADivisExp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisExp4(ADivisExp4 node)
    {
        inADivisExp4(node);
        if(node.getExp4() != null)
        {
            node.getExp4().apply(this);
        }
        if(node.getDivis() != null)
        {
            node.getDivis().apply(this);
        }
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outADivisExp4(node);
    }

    public void inANextExp4(ANextExp4 node)
    {
        defaultIn(node);
    }

    public void outANextExp4(ANextExp4 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANextExp4(ANextExp4 node)
    {
        inANextExp4(node);
        if(node.getExp5() != null)
        {
            node.getExp5().apply(this);
        }
        outANextExp4(node);
    }

    public void inANonExp5(ANonExp5 node)
    {
        defaultIn(node);
    }

    public void outANonExp5(ANonExp5 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANonExp5(ANonExp5 node)
    {
        inANonExp5(node);
        if(node.getNon() != null)
        {
            node.getNon().apply(this);
        }
        if(node.getExp6() != null)
        {
            node.getExp6().apply(this);
        }
        outANonExp5(node);
    }

    public void inANextExp5(ANextExp5 node)
    {
        defaultIn(node);
    }

    public void outANextExp5(ANextExp5 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANextExp5(ANextExp5 node)
    {
        inANextExp5(node);
        if(node.getExp6() != null)
        {
            node.getExp6().apply(this);
        }
        outANextExp5(node);
    }

    public void inAParExp6(AParExp6 node)
    {
        defaultIn(node);
    }

    public void outAParExp6(AParExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParExp6(AParExp6 node)
    {
        inAParExp6(node);
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getExp1() != null)
        {
            node.getExp1().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        outAParExp6(node);
    }

    public void inANumExp6(ANumExp6 node)
    {
        defaultIn(node);
    }

    public void outANumExp6(ANumExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumExp6(ANumExp6 node)
    {
        inANumExp6(node);
        if(node.getNombre() != null)
        {
            node.getNombre().apply(this);
        }
        outANumExp6(node);
    }

    public void inAVarExp6(AVarExp6 node)
    {
        defaultIn(node);
    }

    public void outAVarExp6(AVarExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarExp6(AVarExp6 node)
    {
        inAVarExp6(node);
        if(node.getV() != null)
        {
            node.getV().apply(this);
        }
        outAVarExp6(node);
    }

    public void inAAppfExp6(AAppfExp6 node)
    {
        defaultIn(node);
    }

    public void outAAppfExp6(AAppfExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAppfExp6(AAppfExp6 node)
    {
        inAAppfExp6(node);
        if(node.getAf() != null)
        {
            node.getAf().apply(this);
        }
        outAAppfExp6(node);
    }

    public void inAVraiExp6(AVraiExp6 node)
    {
        defaultIn(node);
    }

    public void outAVraiExp6(AVraiExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVraiExp6(AVraiExp6 node)
    {
        inAVraiExp6(node);
        if(node.getVrai() != null)
        {
            node.getVrai().apply(this);
        }
        outAVraiExp6(node);
    }

    public void inAFauxExp6(AFauxExp6 node)
    {
        defaultIn(node);
    }

    public void outAFauxExp6(AFauxExp6 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFauxExp6(AFauxExp6 node)
    {
        inAFauxExp6(node);
        if(node.getFaux() != null)
        {
            node.getFaux().apply(this);
        }
        outAFauxExp6(node);
    }

    public void inAAffectI(AAffectI node)
    {
        defaultIn(node);
    }

    public void outAAffectI(AAffectI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAffectI(AAffectI node)
    {
        inAAffectI(node);
        if(node.getV() != null)
        {
            node.getV().apply(this);
        }
        if(node.getEgal() != null)
        {
            node.getEgal().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPv() != null)
        {
            node.getPv().apply(this);
        }
        outAAffectI(node);
    }

    public void inATqI(ATqI node)
    {
        defaultIn(node);
    }

    public void outATqI(ATqI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATqI(ATqI node)
    {
        inATqI(node);
        if(node.getTq() != null)
        {
            node.getTq().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getFaire() != null)
        {
            node.getFaire().apply(this);
        }
        if(node.getBi() != null)
        {
            node.getBi().apply(this);
        }
        outATqI(node);
    }

    public void inASiI(ASiI node)
    {
        defaultIn(node);
    }

    public void outASiI(ASiI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASiI(ASiI node)
    {
        inASiI(node);
        if(node.getSi() != null)
        {
            node.getSi().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAlors() != null)
        {
            node.getAlors().apply(this);
        }
        if(node.getBi() != null)
        {
            node.getBi().apply(this);
        }
        outASiI(node);
    }

    public void inASinonI(ASinonI node)
    {
        defaultIn(node);
    }

    public void outASinonI(ASinonI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASinonI(ASinonI node)
    {
        inASinonI(node);
        if(node.getSi() != null)
        {
            node.getSi().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAlors() != null)
        {
            node.getAlors().apply(this);
        }
        if(node.getOui() != null)
        {
            node.getOui().apply(this);
        }
        if(node.getSinon() != null)
        {
            node.getSinon().apply(this);
        }
        if(node.getNon() != null)
        {
            node.getNon().apply(this);
        }
        outASinonI(node);
    }

    public void inARetourI(ARetourI node)
    {
        defaultIn(node);
    }

    public void outARetourI(ARetourI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARetourI(ARetourI node)
    {
        inARetourI(node);
        if(node.getRetour() != null)
        {
            node.getRetour().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPv() != null)
        {
            node.getPv().apply(this);
        }
        outARetourI(node);
    }

    public void inAAppfI(AAppfI node)
    {
        defaultIn(node);
    }

    public void outAAppfI(AAppfI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAppfI(AAppfI node)
    {
        inAAppfI(node);
        if(node.getAf() != null)
        {
            node.getAf().apply(this);
        }
        if(node.getPv() != null)
        {
            node.getPv().apply(this);
        }
        outAAppfI(node);
    }

    public void inAEcrireI(AEcrireI node)
    {
        defaultIn(node);
    }

    public void outAEcrireI(AEcrireI node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEcrireI(AEcrireI node)
    {
        inAEcrireI(node);
        if(node.getEcrire() != null)
        {
            node.getEcrire().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        if(node.getPv() != null)
        {
            node.getPv().apply(this);
        }
        outAEcrireI(node);
    }

    public void inABi(ABi node)
    {
        defaultIn(node);
    }

    public void outABi(ABi node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABi(ABi node)
    {
        inABi(node);
        if(node.getAco() != null)
        {
            node.getAco().apply(this);
        }
        if(node.getLi() != null)
        {
            node.getLi().apply(this);
        }
        if(node.getAcf() != null)
        {
            node.getAcf().apply(this);
        }
        outABi(node);
    }

    public void inARecurLi(ARecurLi node)
    {
        defaultIn(node);
    }

    public void outARecurLi(ARecurLi node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARecurLi(ARecurLi node)
    {
        inARecurLi(node);
        if(node.getLi() != null)
        {
            node.getLi().apply(this);
        }
        if(node.getI() != null)
        {
            node.getI().apply(this);
        }
        outARecurLi(node);
    }

    public void inAVideLi(AVideLi node)
    {
        defaultIn(node);
    }

    public void outAVideLi(AVideLi node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideLi(AVideLi node)
    {
        inAVideLi(node);
        if(node.getEps() != null)
        {
            node.getEps().apply(this);
        }
        outAVideLi(node);
    }

    public void inAEps(AEps node)
    {
        defaultIn(node);
    }

    public void outAEps(AEps node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEps(AEps node)
    {
        inAEps(node);
        outAEps(node);
    }

    public void inAVarDv(AVarDv node)
    {
        defaultIn(node);
    }

    public void outAVarDv(AVarDv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDv(AVarDv node)
    {
        inAVarDv(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAVarDv(node);
    }

    public void inATabDv(ATabDv node)
    {
        defaultIn(node);
    }

    public void outATabDv(ATabDv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATabDv(ATabDv node)
    {
        inATabDv(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCro() != null)
        {
            node.getCro().apply(this);
        }
        if(node.getNombre() != null)
        {
            node.getNombre().apply(this);
        }
        if(node.getCrf() != null)
        {
            node.getCrf().apply(this);
        }
        outATabDv(node);
    }

    public void inADf(ADf node)
    {
        defaultIn(node);
    }

    public void outADf(ADf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADf(ADf node)
    {
        inADf(node);
        if(node.getTypeopt() != null)
        {
            node.getTypeopt().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getParam() != null)
        {
            node.getParam().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        if(node.getVarloc() != null)
        {
            node.getVarloc().apply(this);
        }
        if(node.getBi() != null)
        {
            node.getBi().apply(this);
        }
        outADf(node);
    }

    public void inAVideLdv(AVideLdv node)
    {
        defaultIn(node);
    }

    public void outAVideLdv(AVideLdv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideLdv(AVideLdv node)
    {
        inAVideLdv(node);
        if(node.getEps() != null)
        {
            node.getEps().apply(this);
        }
        outAVideLdv(node);
    }

    public void inAPremLdv(APremLdv node)
    {
        defaultIn(node);
    }

    public void outAPremLdv(APremLdv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPremLdv(APremLdv node)
    {
        inAPremLdv(node);
        if(node.getDv() != null)
        {
            node.getDv().apply(this);
        }
        if(node.getLdvb() != null)
        {
            node.getLdvb().apply(this);
        }
        outAPremLdv(node);
    }

    public void inAVideLdvb(AVideLdvb node)
    {
        defaultIn(node);
    }

    public void outAVideLdvb(AVideLdvb node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideLdvb(AVideLdvb node)
    {
        inAVideLdvb(node);
        if(node.getEps() != null)
        {
            node.getEps().apply(this);
        }
        outAVideLdvb(node);
    }

    public void inASuiteLdvb(ASuiteLdvb node)
    {
        defaultIn(node);
    }

    public void outASuiteLdvb(ASuiteLdvb node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASuiteLdvb(ASuiteLdvb node)
    {
        inASuiteLdvb(node);
        if(node.getVir() != null)
        {
            node.getVir().apply(this);
        }
        if(node.getDv() != null)
        {
            node.getDv().apply(this);
        }
        if(node.getLdvb() != null)
        {
            node.getLdvb().apply(this);
        }
        outASuiteLdvb(node);
    }

    public void inAVideTypeopt(AVideTypeopt node)
    {
        defaultIn(node);
    }

    public void outAVideTypeopt(AVideTypeopt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideTypeopt(AVideTypeopt node)
    {
        inAVideTypeopt(node);
        if(node.getEps() != null)
        {
            node.getEps().apply(this);
        }
        outAVideTypeopt(node);
    }

    public void inATypeTypeopt(ATypeTypeopt node)
    {
        defaultIn(node);
    }

    public void outATypeTypeopt(ATypeTypeopt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATypeTypeopt(ATypeTypeopt node)
    {
        inATypeTypeopt(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outATypeTypeopt(node);
    }

    public void inAIntType(AIntType node)
    {
        defaultIn(node);
    }

    public void outAIntType(AIntType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntType(AIntType node)
    {
        inAIntType(node);
        if(node.getEntier() != null)
        {
            node.getEntier().apply(this);
        }
        outAIntType(node);
    }

    public void inABoolType(ABoolType node)
    {
        defaultIn(node);
    }

    public void outABoolType(ABoolType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABoolType(ABoolType node)
    {
        inABoolType(node);
        if(node.getBool() != null)
        {
            node.getBool().apply(this);
        }
        outABoolType(node);
    }

    public void inAVarV(AVarV node)
    {
        defaultIn(node);
    }

    public void outAVarV(AVarV node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarV(AVarV node)
    {
        inAVarV(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAVarV(node);
    }

    public void inATabV(ATabV node)
    {
        defaultIn(node);
    }

    public void outATabV(ATabV node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATabV(ATabV node)
    {
        inATabV(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getCro() != null)
        {
            node.getCro().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getCrf() != null)
        {
            node.getCrf().apply(this);
        }
        outATabV(node);
    }

    public void inAAf(AAf node)
    {
        defaultIn(node);
    }

    public void outAAf(AAf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAf(AAf node)
    {
        inAAf(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPo() != null)
        {
            node.getPo().apply(this);
        }
        if(node.getLe() != null)
        {
            node.getLe().apply(this);
        }
        if(node.getPf() != null)
        {
            node.getPf().apply(this);
        }
        outAAf(node);
    }

    public void inAVideLe(AVideLe node)
    {
        defaultIn(node);
    }

    public void outAVideLe(AVideLe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideLe(AVideLe node)
    {
        inAVideLe(node);
        if(node.getEps() != null)
        {
            node.getEps().apply(this);
        }
        outAVideLe(node);
    }

    public void inAPremLe(APremLe node)
    {
        defaultIn(node);
    }

    public void outAPremLe(APremLe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPremLe(APremLe node)
    {
        inAPremLe(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getLeb() != null)
        {
            node.getLeb().apply(this);
        }
        outAPremLe(node);
    }

    public void inAVideLeb(AVideLeb node)
    {
        defaultIn(node);
    }

    public void outAVideLeb(AVideLeb node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideLeb(AVideLeb node)
    {
        inAVideLeb(node);
        if(node.getEps() != null)
        {
            node.getEps().apply(this);
        }
        outAVideLeb(node);
    }

    public void inASuiteLeb(ASuiteLeb node)
    {
        defaultIn(node);
    }

    public void outASuiteLeb(ASuiteLeb node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASuiteLeb(ASuiteLeb node)
    {
        inASuiteLeb(node);
        if(node.getVir() != null)
        {
            node.getVir().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getLeb() != null)
        {
            node.getLeb().apply(this);
        }
        outASuiteLeb(node);
    }

    public void inAVideLdf(AVideLdf node)
    {
        defaultIn(node);
    }

    public void outAVideLdf(AVideLdf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVideLdf(AVideLdf node)
    {
        inAVideLdf(node);
        if(node.getEps() != null)
        {
            node.getEps().apply(this);
        }
        outAVideLdf(node);
    }

    public void inAElemLdf(AElemLdf node)
    {
        defaultIn(node);
    }

    public void outAElemLdf(AElemLdf node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElemLdf(AElemLdf node)
    {
        inAElemLdf(node);
        if(node.getDf() != null)
        {
            node.getDf().apply(this);
        }
        if(node.getLdf() != null)
        {
            node.getLdf().apply(this);
        }
        outAElemLdf(node);
    }
}
