/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AAppfExp6 extends PExp6
{
    private PAf _af_;

    public AAppfExp6()
    {
        // Constructor
    }

    public AAppfExp6(
        @SuppressWarnings("hiding") PAf _af_)
    {
        // Constructor
        setAf(_af_);

    }

    @Override
    public Object clone()
    {
        return new AAppfExp6(
            cloneNode(this._af_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppfExp6(this);
    }

    public PAf getAf()
    {
        return this._af_;
    }

    public void setAf(PAf node)
    {
        if(this._af_ != null)
        {
            this._af_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._af_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._af_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._af_ == child)
        {
            this._af_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._af_ == oldChild)
        {
            setAf((PAf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
