/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AAppfI extends PI
{
    private PAf _af_;
    private TPv _pv_;

    public AAppfI()
    {
        // Constructor
    }

    public AAppfI(
        @SuppressWarnings("hiding") PAf _af_,
        @SuppressWarnings("hiding") TPv _pv_)
    {
        // Constructor
        setAf(_af_);

        setPv(_pv_);

    }

    @Override
    public Object clone()
    {
        return new AAppfI(
            cloneNode(this._af_),
            cloneNode(this._pv_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAppfI(this);
    }

    public PAf getAf()
    {
        return this._af_;
    }

    public void setAf(PAf node)
    {
        if(this._af_ != null)
        {
            this._af_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._af_ = node;
    }

    public TPv getPv()
    {
        return this._pv_;
    }

    public void setPv(TPv node)
    {
        if(this._pv_ != null)
        {
            this._pv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pv_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._af_)
            + toString(this._pv_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._af_ == child)
        {
            this._af_ = null;
            return;
        }

        if(this._pv_ == child)
        {
            this._pv_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._af_ == oldChild)
        {
            setAf((PAf) newChild);
            return;
        }

        if(this._pv_ == oldChild)
        {
            setPv((TPv) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
