/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ABi extends PBi
{
    private TAco _aco_;
    private PLi _li_;
    private TAcf _acf_;

    public ABi()
    {
        // Constructor
    }

    public ABi(
        @SuppressWarnings("hiding") TAco _aco_,
        @SuppressWarnings("hiding") PLi _li_,
        @SuppressWarnings("hiding") TAcf _acf_)
    {
        // Constructor
        setAco(_aco_);

        setLi(_li_);

        setAcf(_acf_);

    }

    @Override
    public Object clone()
    {
        return new ABi(
            cloneNode(this._aco_),
            cloneNode(this._li_),
            cloneNode(this._acf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABi(this);
    }

    public TAco getAco()
    {
        return this._aco_;
    }

    public void setAco(TAco node)
    {
        if(this._aco_ != null)
        {
            this._aco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aco_ = node;
    }

    public PLi getLi()
    {
        return this._li_;
    }

    public void setLi(PLi node)
    {
        if(this._li_ != null)
        {
            this._li_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._li_ = node;
    }

    public TAcf getAcf()
    {
        return this._acf_;
    }

    public void setAcf(TAcf node)
    {
        if(this._acf_ != null)
        {
            this._acf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._acf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aco_)
            + toString(this._li_)
            + toString(this._acf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aco_ == child)
        {
            this._aco_ = null;
            return;
        }

        if(this._li_ == child)
        {
            this._li_ = null;
            return;
        }

        if(this._acf_ == child)
        {
            this._acf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aco_ == oldChild)
        {
            setAco((TAco) newChild);
            return;
        }

        if(this._li_ == oldChild)
        {
            setLi((PLi) newChild);
            return;
        }

        if(this._acf_ == oldChild)
        {
            setAcf((TAcf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
