/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ADf extends PDf
{
    private PTypeopt _typeopt_;
    private TId _id_;
    private TPo _po_;
    private PLdv _param_;
    private TPf _pf_;
    private PLdv _varloc_;
    private PBi _bi_;

    public ADf()
    {
        // Constructor
    }

    public ADf(
        @SuppressWarnings("hiding") PTypeopt _typeopt_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TPo _po_,
        @SuppressWarnings("hiding") PLdv _param_,
        @SuppressWarnings("hiding") TPf _pf_,
        @SuppressWarnings("hiding") PLdv _varloc_,
        @SuppressWarnings("hiding") PBi _bi_)
    {
        // Constructor
        setTypeopt(_typeopt_);

        setId(_id_);

        setPo(_po_);

        setParam(_param_);

        setPf(_pf_);

        setVarloc(_varloc_);

        setBi(_bi_);

    }

    @Override
    public Object clone()
    {
        return new ADf(
            cloneNode(this._typeopt_),
            cloneNode(this._id_),
            cloneNode(this._po_),
            cloneNode(this._param_),
            cloneNode(this._pf_),
            cloneNode(this._varloc_),
            cloneNode(this._bi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADf(this);
    }

    public PTypeopt getTypeopt()
    {
        return this._typeopt_;
    }

    public void setTypeopt(PTypeopt node)
    {
        if(this._typeopt_ != null)
        {
            this._typeopt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._typeopt_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TPo getPo()
    {
        return this._po_;
    }

    public void setPo(TPo node)
    {
        if(this._po_ != null)
        {
            this._po_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._po_ = node;
    }

    public PLdv getParam()
    {
        return this._param_;
    }

    public void setParam(PLdv node)
    {
        if(this._param_ != null)
        {
            this._param_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._param_ = node;
    }

    public TPf getPf()
    {
        return this._pf_;
    }

    public void setPf(TPf node)
    {
        if(this._pf_ != null)
        {
            this._pf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pf_ = node;
    }

    public PLdv getVarloc()
    {
        return this._varloc_;
    }

    public void setVarloc(PLdv node)
    {
        if(this._varloc_ != null)
        {
            this._varloc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varloc_ = node;
    }

    public PBi getBi()
    {
        return this._bi_;
    }

    public void setBi(PBi node)
    {
        if(this._bi_ != null)
        {
            this._bi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._typeopt_)
            + toString(this._id_)
            + toString(this._po_)
            + toString(this._param_)
            + toString(this._pf_)
            + toString(this._varloc_)
            + toString(this._bi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._typeopt_ == child)
        {
            this._typeopt_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._po_ == child)
        {
            this._po_ = null;
            return;
        }

        if(this._param_ == child)
        {
            this._param_ = null;
            return;
        }

        if(this._pf_ == child)
        {
            this._pf_ = null;
            return;
        }

        if(this._varloc_ == child)
        {
            this._varloc_ = null;
            return;
        }

        if(this._bi_ == child)
        {
            this._bi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._typeopt_ == oldChild)
        {
            setTypeopt((PTypeopt) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._po_ == oldChild)
        {
            setPo((TPo) newChild);
            return;
        }

        if(this._param_ == oldChild)
        {
            setParam((PLdv) newChild);
            return;
        }

        if(this._pf_ == oldChild)
        {
            setPf((TPf) newChild);
            return;
        }

        if(this._varloc_ == oldChild)
        {
            setVarloc((PLdv) newChild);
            return;
        }

        if(this._bi_ == oldChild)
        {
            setBi((PBi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
