/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class APremLe extends PLe
{
    private PExp _exp_;
    private PLeb _leb_;

    public APremLe()
    {
        // Constructor
    }

    public APremLe(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PLeb _leb_)
    {
        // Constructor
        setExp(_exp_);

        setLeb(_leb_);

    }

    @Override
    public Object clone()
    {
        return new APremLe(
            cloneNode(this._exp_),
            cloneNode(this._leb_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPremLe(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PLeb getLeb()
    {
        return this._leb_;
    }

    public void setLeb(PLeb node)
    {
        if(this._leb_ != null)
        {
            this._leb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leb_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._leb_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._leb_ == child)
        {
            this._leb_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._leb_ == oldChild)
        {
            setLeb((PLeb) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
