/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ARecurLi extends PLi
{
    private PLi _li_;
    private PI _i_;

    public ARecurLi()
    {
        // Constructor
    }

    public ARecurLi(
        @SuppressWarnings("hiding") PLi _li_,
        @SuppressWarnings("hiding") PI _i_)
    {
        // Constructor
        setLi(_li_);

        setI(_i_);

    }

    @Override
    public Object clone()
    {
        return new ARecurLi(
            cloneNode(this._li_),
            cloneNode(this._i_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecurLi(this);
    }

    public PLi getLi()
    {
        return this._li_;
    }

    public void setLi(PLi node)
    {
        if(this._li_ != null)
        {
            this._li_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._li_ = node;
    }

    public PI getI()
    {
        return this._i_;
    }

    public void setI(PI node)
    {
        if(this._i_ != null)
        {
            this._i_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._i_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._li_)
            + toString(this._i_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._li_ == child)
        {
            this._li_ = null;
            return;
        }

        if(this._i_ == child)
        {
            this._i_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._li_ == oldChild)
        {
            setLi((PLi) newChild);
            return;
        }

        if(this._i_ == oldChild)
        {
            setI((PI) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
