/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ASinonI extends PI
{
    private TSi _si_;
    private PExp _exp_;
    private TAlors _alors_;
    private PBi _oui_;
    private TSinon _sinon_;
    private PBi _non_;

    public ASinonI()
    {
        // Constructor
    }

    public ASinonI(
        @SuppressWarnings("hiding") TSi _si_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TAlors _alors_,
        @SuppressWarnings("hiding") PBi _oui_,
        @SuppressWarnings("hiding") TSinon _sinon_,
        @SuppressWarnings("hiding") PBi _non_)
    {
        // Constructor
        setSi(_si_);

        setExp(_exp_);

        setAlors(_alors_);

        setOui(_oui_);

        setSinon(_sinon_);

        setNon(_non_);

    }

    @Override
    public Object clone()
    {
        return new ASinonI(
            cloneNode(this._si_),
            cloneNode(this._exp_),
            cloneNode(this._alors_),
            cloneNode(this._oui_),
            cloneNode(this._sinon_),
            cloneNode(this._non_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinonI(this);
    }

    public TSi getSi()
    {
        return this._si_;
    }

    public void setSi(TSi node)
    {
        if(this._si_ != null)
        {
            this._si_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._si_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TAlors getAlors()
    {
        return this._alors_;
    }

    public void setAlors(TAlors node)
    {
        if(this._alors_ != null)
        {
            this._alors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alors_ = node;
    }

    public PBi getOui()
    {
        return this._oui_;
    }

    public void setOui(PBi node)
    {
        if(this._oui_ != null)
        {
            this._oui_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oui_ = node;
    }

    public TSinon getSinon()
    {
        return this._sinon_;
    }

    public void setSinon(TSinon node)
    {
        if(this._sinon_ != null)
        {
            this._sinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinon_ = node;
    }

    public PBi getNon()
    {
        return this._non_;
    }

    public void setNon(PBi node)
    {
        if(this._non_ != null)
        {
            this._non_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._non_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._si_)
            + toString(this._exp_)
            + toString(this._alors_)
            + toString(this._oui_)
            + toString(this._sinon_)
            + toString(this._non_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._si_ == child)
        {
            this._si_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._alors_ == child)
        {
            this._alors_ = null;
            return;
        }

        if(this._oui_ == child)
        {
            this._oui_ = null;
            return;
        }

        if(this._sinon_ == child)
        {
            this._sinon_ = null;
            return;
        }

        if(this._non_ == child)
        {
            this._non_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._si_ == oldChild)
        {
            setSi((TSi) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._alors_ == oldChild)
        {
            setAlors((TAlors) newChild);
            return;
        }

        if(this._oui_ == oldChild)
        {
            setOui((PBi) newChild);
            return;
        }

        if(this._sinon_ == oldChild)
        {
            setSinon((TSinon) newChild);
            return;
        }

        if(this._non_ == oldChild)
        {
            setNon((PBi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
