/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ASuiteLeb extends PLeb
{
    private TVir _vir_;
    private PExp _exp_;
    private PLeb _leb_;

    public ASuiteLeb()
    {
        // Constructor
    }

    public ASuiteLeb(
        @SuppressWarnings("hiding") TVir _vir_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PLeb _leb_)
    {
        // Constructor
        setVir(_vir_);

        setExp(_exp_);

        setLeb(_leb_);

    }

    @Override
    public Object clone()
    {
        return new ASuiteLeb(
            cloneNode(this._vir_),
            cloneNode(this._exp_),
            cloneNode(this._leb_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuiteLeb(this);
    }

    public TVir getVir()
    {
        return this._vir_;
    }

    public void setVir(TVir node)
    {
        if(this._vir_ != null)
        {
            this._vir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vir_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PLeb getLeb()
    {
        return this._leb_;
    }

    public void setLeb(PLeb node)
    {
        if(this._leb_ != null)
        {
            this._leb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leb_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vir_)
            + toString(this._exp_)
            + toString(this._leb_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vir_ == child)
        {
            this._vir_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._leb_ == child)
        {
            this._leb_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vir_ == oldChild)
        {
            setVir((TVir) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._leb_ == oldChild)
        {
            setLeb((PLeb) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
