/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ASuiteLdvb extends PLdvb
{
    private TVir _vir_;
    private PDv _dv_;
    private PLdvb _ldvb_;

    public ASuiteLdvb()
    {
        // Constructor
    }

    public ASuiteLdvb(
        @SuppressWarnings("hiding") TVir _vir_,
        @SuppressWarnings("hiding") PDv _dv_,
        @SuppressWarnings("hiding") PLdvb _ldvb_)
    {
        // Constructor
        setVir(_vir_);

        setDv(_dv_);

        setLdvb(_ldvb_);

    }

    @Override
    public Object clone()
    {
        return new ASuiteLdvb(
            cloneNode(this._vir_),
            cloneNode(this._dv_),
            cloneNode(this._ldvb_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuiteLdvb(this);
    }

    public TVir getVir()
    {
        return this._vir_;
    }

    public void setVir(TVir node)
    {
        if(this._vir_ != null)
        {
            this._vir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vir_ = node;
    }

    public PDv getDv()
    {
        return this._dv_;
    }

    public void setDv(PDv node)
    {
        if(this._dv_ != null)
        {
            this._dv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dv_ = node;
    }

    public PLdvb getLdvb()
    {
        return this._ldvb_;
    }

    public void setLdvb(PLdvb node)
    {
        if(this._ldvb_ != null)
        {
            this._ldvb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ldvb_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vir_)
            + toString(this._dv_)
            + toString(this._ldvb_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vir_ == child)
        {
            this._vir_ = null;
            return;
        }

        if(this._dv_ == child)
        {
            this._dv_ = null;
            return;
        }

        if(this._ldvb_ == child)
        {
            this._ldvb_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vir_ == oldChild)
        {
            setVir((TVir) newChild);
            return;
        }

        if(this._dv_ == oldChild)
        {
            setDv((PDv) newChild);
            return;
        }

        if(this._ldvb_ == oldChild)
        {
            setLdvb((PLdvb) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
