/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class ATabV extends PV
{
    private TId _id_;
    private TCro _cro_;
    private PExp _exp_;
    private TCrf _crf_;

    public ATabV()
    {
        // Constructor
    }

    public ATabV(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TCro _cro_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TCrf _crf_)
    {
        // Constructor
        setId(_id_);

        setCro(_cro_);

        setExp(_exp_);

        setCrf(_crf_);

    }

    @Override
    public Object clone()
    {
        return new ATabV(
            cloneNode(this._id_),
            cloneNode(this._cro_),
            cloneNode(this._exp_),
            cloneNode(this._crf_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATabV(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TCro getCro()
    {
        return this._cro_;
    }

    public void setCro(TCro node)
    {
        if(this._cro_ != null)
        {
            this._cro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cro_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TCrf getCrf()
    {
        return this._crf_;
    }

    public void setCrf(TCrf node)
    {
        if(this._crf_ != null)
        {
            this._crf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._cro_)
            + toString(this._exp_)
            + toString(this._crf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._cro_ == child)
        {
            this._cro_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._crf_ == child)
        {
            this._crf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._cro_ == oldChild)
        {
            setCro((TCro) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._crf_ == oldChild)
        {
            setCrf((TCrf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
