/* This file was generated by SableCC (http://www.sablecc.org/). */

package lParser.node;

import lParser.analysis.*;

@SuppressWarnings("nls")
public final class AVarExp6 extends PExp6
{
    private PV _v_;

    public AVarExp6()
    {
        // Constructor
    }

    public AVarExp6(
        @SuppressWarnings("hiding") PV _v_)
    {
        // Constructor
        setV(_v_);

    }

    @Override
    public Object clone()
    {
        return new AVarExp6(
            cloneNode(this._v_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarExp6(this);
    }

    public PV getV()
    {
        return this._v_;
    }

    public void setV(PV node)
    {
        if(this._v_ != null)
        {
            this._v_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._v_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._v_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._v_ == child)
        {
            this._v_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._v_ == oldChild)
        {
            setV((PV) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
